# NOTE: Workflow disabled
name: Notify Discord

on:
  workflow_dispatch:

jobs:
  notify:
    if: ${{ false }}
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 23
      - run: npm ci
      - run: npx ts-node --transpile-only deploy/discord.ts